-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS s18d5.author
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    first_name character varying(50),
    last_name character varying(50),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS s18d5.book
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( CYCLE INCREMENT 1 START 1 ),
    name character varying(100) NOT NULL,
    category_id bigint,
    author_id bigint,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS s18d5.category
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    name character varying(75) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS s18d5.book
    ADD FOREIGN KEY (author_id)
    REFERENCES s18d5.author (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS s18d5.book
    ADD FOREIGN KEY (category_id)
    REFERENCES s18d5.category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;